sonar.projectKey=carnival-project
sonar.projectName=CARNIVAL Generated Project
sonar.sources=src/main/java,src/main/webapp
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/*.spec.ts,**/node_modules/**